# Generated by Django 5.2.5 on 2025-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
